---
abstract: 'Composite Type handler for PGObject'
author:
  - 'Chris Travers <chris.travers@gmail.com>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGObject-Type-Composite
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
resources:
  repository: https://github.com/ledgersmb/PGObject-Type-Composite.git
version: 0.01
